### ISSUE TITLE
Blue background of icon instead of transparent color

### ISSUE THREAD

**Issue by dmitrya1979** [tfennel/desktop-toasts#12]
@andrewleader, @MichaelGoulding If application icon has transparent areas then it is displayed as blue color. Sample has a "default icon" and looks like image below :

![iconbackground](https://user-images.githubusercontent.com/14328243/51747435-935f1a00-20ba-11e9-9988-a1cd8c1f2c73.png)

If I use icon of our application (with transparent area), then it is also displays blue color instead of transparent area. Can it be fixed?

**Comment by andrewleader** [comment]
Hey Dmitry, thanks for asking. Mary Anne from the notifications team is looking into this!

**Comment by dmitrya1979** [comment]
@andrewleader thank you! Were you able to find reason of blue background for transparent icons?

**Comment by andrewleader** [comment]
Hey Dmitry, sorry for never getting back to you. Classic Win32 apps will always have the accent color background on the icon (in your case, your computer's accent color is set to blue). It's a new feature request for Windows to allow Classic Win32 apps to have "unplated" app icons (with no background).

Since a few people have asked for this, the notifications team will consider looking into enabling this feature in the future, but they have no timeline to share.

In the meantime, you can use [Desktop Bridge](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root) with your Win32 app, and then you can use unplated icons, publish your app to the Store, and more. Let us know if you need any help switching to Desktop Bridge!

Closing this issue, but feel free to comment with more questions.
